$.Lng.SETUP = 'Setup';
$.Lng.SETUP_TITLE = "Configuration";
$.Lng.OLD_PASSWORD = "Old password";
$.Lng.NEW_PASSWORD = "New password";
$.Lng.NEW_PASSWORD2 = "New password retype";
$.Lng.ENABLED_DNA_HASHES = "Enabled DNA Hashes";
$.Lng.PASSWORDS_NOT_EQUAL = "Passwords not equal";
$.Lng.WRONG_PASSWORD = "Wrong password";
$.lng.CHANGE_PSW = "if you want to modify the password";
$.lng.DNA_HELP = "(only one DNA hash in one line)"